name: database
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./docker/postgres.dockerfile
    restart: always
    shm_size: 256mb
    environment:
      - POSTGRES_USER=server_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    # volumes:
      # - local_pgdata:/var/lib/postgresql/data
      # - $(pwd)/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - database
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   depends_on:
  #     postgres: 
  #       condition: service_healthy
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=server@debian.home
  #     - PGADMIN_DEFAULT_PASSWORD=password123
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - proxy
  #     - database
  liquibase-update:
    container_name: liquibase-update
    image: liquibase
    depends_on:
      postgres: 
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command: update --driver=org.postgresql.Driver
            --url="jdbc:postgresql://postgres:5432/dev"
            --changeLogFile=changelog/root_changelog.xml --username=server_ddl
            --password=testing --liquibase-schema-name=liquibase
    networks:
      - database


# volumes:
  # local_pgdata:
  # pgadmin-data:

networks:
  database: